#!/usr/bin/env python3
"""
rotation_tracker.py — watch how active option-income funds rotate their basket.

Some of these funds turn their holdings over actively; this turns the daily
holdings history into a readable rotation report per fund so the drift is
visible as it happens instead of reconstructed after the fact.

Funds tracked (see FUNDS below):
  • ULTI (REX)      — grouped by THEME. Aggressive thematic rotator: rebuilds
                      its speculative basket almost entirely month to month
                      (nuclear/uranium in May -> quantum by June 2026).
  • ULTY (YieldMax) — grouped by SECTOR. Modest quarterly rotation of a
                      high-IV large-cap basket (swaps a handful of names/quarter).

KYLD/KQQQ (Kurv) are deliberately NOT here — they hold a static large-cap basket
(0% roster churn), so a rotation view would be flat lines.

Outputs per fund (regenerated by the daily scrape pipeline):
  • analyses/<fund>_rotation.md                      — human-readable report
  • etf-dashboard/public/data/<fund>_rotation.json   — machine-readable (dashboard)

Run standalone any time:
    python3 scripts/rotation_tracker.py

A holding not in a fund's map lands in an "Uncategorized" bucket and is flagged
at the top of the report — add it to the relevant map below. Nothing breaks if
you never do; it just shows as Uncategorized.
"""
import csv
import glob
import json
import os
from collections import defaultdict, OrderedDict
from datetime import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HISTORY = os.path.join(ROOT, "etf-dashboard", "public", "data", "history")
ANALYSES = os.path.join(ROOT, "analyses")
PUBLIC = os.path.join(ROOT, "etf-dashboard", "public", "data")

# ── ULTI: thematic speculative basket. Extend as it rotates into new names. ──
THEME = {
    "CLSK": "Bitcoin miners", "RIOT": "Bitcoin miners", "CIFR": "Bitcoin miners",
    "WULF": "Bitcoin miners", "CORZ": "Bitcoin miners", "IREN": "Bitcoin miners",
    "APLD": "Bitcoin miners", "MARA": "Bitcoin miners", "BTDR": "Bitcoin miners",
    "HUT": "Bitcoin miners", "BITF": "Bitcoin miners",
    "IONQ": "Quantum", "RGTI": "Quantum", "QBTS": "Quantum", "QUBT": "Quantum",
    "ASTS": "Space", "LUNR": "Space", "RDW": "Space", "RKLB": "Space", "PL": "Space",
    "USAR": "Rare earth/materials", "TE": "Rare earth/materials", "MP": "Rare earth/materials",
    "CRML": "Rare earth/materials", "UAMY": "Rare earth/materials",
    "ONDS": "Drones/defense", "UMAC": "Drones/defense", "RCAT": "Drones/defense",
    "KTOS": "Drones/defense", "AVAV": "Drones/defense",
    "POET": "Semis/photonics", "NVTS": "Semis/photonics", "WOLF": "Semis/photonics",
    "AXTI": "Semis/photonics", "LITE": "Semis/photonics", "AAOI": "Semis/photonics",
    "CRDO": "Semis/photonics", "AEHR": "Semis/photonics", "LWLG": "Semis/photonics",
    "ENPH": "Clean energy", "FCEL": "Clean energy", "SEDG": "Clean energy",
    "BE": "Clean energy", "PLUG": "Clean energy", "RUN": "Clean energy",
    "OKLO": "Nuclear/uranium", "SMR": "Nuclear/uranium", "UEC": "Nuclear/uranium",
    "UUUU": "Nuclear/uranium", "LEU": "Nuclear/uranium",
    "GLXY": "Crypto financials", "COIN": "Crypto financials", "BMNR": "Crypto financials",
    "HOOD": "Crypto financials", "CRCL": "Crypto financials", "ASST.UQ": "Crypto financials",
    "CRWV": "Cloud/AI", "NBIS": "Cloud/AI", "PATH": "Cloud/AI", "FSLY": "Cloud/AI",
    "TTD": "Cloud/AI", "DOCN": "Cloud/AI",
    "UPST": "Fintech", "SOFI": "Fintech", "AFRM": "Fintech", "KLAR": "Fintech",
    "LMND": "Fintech", "FIGR": "Fintech",
    "HIMS": "Healthcare/biotech", "SMMT": "Healthcare/biotech", "OCUL": "Healthcare/biotech",
    "LQDA": "Healthcare/biotech",
    "ALAB": "Semis/photonics", "COHR": "Semis/photonics", "INTC": "Semis/photonics",
    "SNDK": "Semis/photonics", "OUST": "Semis/photonics", "FCEL.UQ": "Clean energy",
    "FLY": "Space", "AMPX": "Battery", "CDE": "Precious metals", "BW": "Industrials",
    "PCT": "Other", "CAR": "Other", "SOC": "Other", "VG": "Other",
}

# ── ULTY: high-IV large-cap basket, grouped by GICS-style sector. ──
SECTOR = {
    # Technology (semis, hardware, software, photonics)
    "ADI": "Technology", "ALAB": "Technology", "AMD": "Technology", "CIEN": "Technology",
    "COHR": "Technology", "DELL": "Technology", "FTNT": "Technology", "INTU": "Technology",
    "JBL": "Technology", "LITE": "Technology", "LRCX": "Technology", "MDB": "Technology",
    "NVDA": "Technology", "PLTR": "Technology", "SHOP": "Technology",
    # Communication services
    "GOOGL": "Communications", "RBLX": "Communications", "RDDT": "Communications",
    # Consumer
    "AMZN": "Consumer", "MELI": "Consumer",
    # Industrials (incl. small modular nuclear / power infra)
    "CAT": "Industrials", "FIX": "Industrials", "PWR": "Industrials", "SMR": "Industrials",
    # Materials / miners
    "GDX": "Materials", "SCCO": "Materials", "SILJ": "Materials",
    # Financials
    "HOOD": "Financials",
    # Crypto proxies
    "IREN": "Crypto", "MSTR": "Crypto",
    # Healthcare
    "TMDX": "Healthcare",
}

FUNDS = {
    "ULTI": {
        "map": THEME, "groupBy": "theme",
        "blurb": "ULTI rebuilds its speculative basket aggressively — this tracks how "
                 "its theme weights drift and which names rotate in and out, week over week.",
    },
    "ULTY": {
        "map": SECTOR, "groupBy": "sector",
        "blurb": "ULTY actively rotates a high-IV large-cap basket by IV/momentum — this "
                 "tracks its sector tilt and which names rotate in and out over time.",
    },
}


def _f(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def load_equities(path, fund):
    """{ticker: weight%} for the fund's equity sleeve (excludes options/cash/MMF)."""
    out = {}
    with open(path, newline="") as f:
        for r in csv.DictReader(f):
            if r.get("ETF Ticker") != fund or (r.get("Option_Type") or "").strip():
                continue
            tk = (r.get("Ticker") or "").strip()
            name = (r.get("Name") or "").upper()
            if (tk in ("", "OTHER", "CASH", "Cash&Other") or tk.upper().startswith("CASH")
                    or "FGXXX" in tk or "GOVT" in name or "MMKT" in name or "CASH" in name
                    or "TREASURY" in name or "BILL" in name):
                continue
            w = _f(r.get("Weight")) or 0.0
            if w > 0:
                out[tk] = out.get(tk, 0.0) + w
    return out


def weekly_samples(fund):
    """One snapshot per ISO week (the latest date in each week), oldest->newest."""
    by_week = OrderedDict()
    for path in sorted(glob.glob(os.path.join(HISTORY, "holdings_*.csv"))):
        ds = os.path.basename(path)[len("holdings_"):-len(".csv")]
        try:
            d = datetime.strptime(ds, "%Y-%m-%d").date()
        except ValueError:
            continue
        eq = load_equities(path, fund)
        if not eq:
            continue
        by_week[d.isocalendar()[:2]] = (ds, eq)
    return list(by_week.values())


def group_weights(eq, classmap):
    g = defaultdict(float)
    for tk, w in eq.items():
        g[classmap.get(tk, "Uncategorized")] += w
    return dict(g)


def build(fund, cfg):
    classmap = cfg["map"]
    samples = weekly_samples(fund)
    if not samples:
        return None
    samples = samples[-12:]  # last ~12 weeks keeps the timeline readable
    dates = [d for d, _ in samples]
    weights = [group_weights(eq, classmap) for _, eq in samples]
    rosters = [set(eq) for _, eq in samples]

    all_groups = sorted({g for w in weights for g in w}, key=lambda g: -weights[-1].get(g, 0.0))
    latest_eq = samples[-1][1]
    unmapped = sorted(tk for tk in latest_eq if tk not in classmap)

    added = sorted(rosters[-1] - rosters[-2]) if len(rosters) > 1 else []
    dropped = sorted(rosters[-2] - rosters[-1]) if len(rosters) > 1 else []
    held = sorted(rosters[-1] & rosters[-2]) if len(rosters) > 1 else sorted(rosters[-1])
    churn = (len(added) / len(rosters[-1])) if rosters[-1] else 0.0

    payload = {
        "fund": fund,
        "groupBy": cfg["groupBy"],
        "blurb": cfg["blurb"],
        "asOf": dates[-1],
        "holdings": len(latest_eq),
        "dates": dates,
        "themes": all_groups,  # generic group key — kept as 'themes' for the component
        "timeline": [{"date": d, "weights": w} for d, w in zip(dates, weights)],
        "currentThemes": {g: round(weights[-1].get(g, 0.0), 1) for g in all_groups},
        "churnSincePrior": {"added": added, "dropped": dropped, "held": held,
                            "rate": round(churn, 2)},
        "unmapped": unmapped,
    }
    return payload, dates, all_groups, weights


def render_md(payload, dates, groups, weights):
    label = payload["groupBy"].capitalize()
    L = [f"# {payload['fund']} — {label} Rotation & Roster Churn\n"]
    L.append(f"_Auto-generated from daily holdings. As of **{payload['asOf']}** "
             f"· {payload['holdings']} holdings · last {len(dates)} weekly samples._\n")
    if payload["unmapped"]:
        L.append(f"> ⚠️ **Uncategorized tickers** (add to the map in the tracker): "
                 f"{', '.join(payload['unmapped'])}\n")

    L.append(f"## Current {payload['groupBy']} allocation\n")
    L.append(f"| {label} | Weight |"); L.append("|------|-------:|")
    for g in groups:
        w = payload["currentThemes"].get(g, 0.0)
        if w > 0:
            L.append(f"| {g} | {w:.1f}% |")
    L.append("")

    L.append(f"## {label}-weight drift (weekly)\n")
    L.append(f"| {label} | " + " | ".join(d[5:] for d in dates) + " |")
    L.append("|------|" + "|".join(["----:"] * len(dates)) + "|")
    for g in groups:
        row = [f"{w.get(g, 0.0):.0f}" if w.get(g, 0.0) > 0 else "·" for w in weights]
        L.append(f"| {g} | " + " | ".join(row) + " |")
    L.append("")

    c = payload["churnSincePrior"]
    L.append("## Roster churn (latest week vs prior sample)\n")
    L.append(f"- **{int(c['rate']*100)}% of the book turned over** this step.")
    if c["added"]:
        L.append(f"- 🟢 **Added:** {', '.join(c['added'])}")
    if c["dropped"]:
        L.append(f"- 🔴 **Dropped:** {', '.join(c['dropped'])}")
    L.append(f"- ⚪ **Held:** {', '.join(c['held']) if c['held'] else '(none)'}")
    L.append("")
    return "\n".join(L)


def main():
    os.makedirs(ANALYSES, exist_ok=True)
    os.makedirs(PUBLIC, exist_ok=True)
    for fund, cfg in FUNDS.items():
        res = build(fund, cfg)
        if not res:
            print(f"{fund}: no history, skipped"); continue
        payload, dates, groups, weights = res
        slug = fund.lower()
        with open(os.path.join(ANALYSES, f"{slug}_rotation.md"), "w") as f:
            f.write(render_md(payload, dates, groups, weights))
        with open(os.path.join(PUBLIC, f"{slug}_rotation.json"), "w") as f:
            json.dump(payload, f, indent=2)
        msg = (f"{fund}: wrote {slug}_rotation.(md|json) — {payload['holdings']} holdings, "
               f"as of {payload['asOf']}")
        if payload["unmapped"]:
            msg += f" · UNCATEGORIZED: {', '.join(payload['unmapped'])}"
        print(msg)


if __name__ == "__main__":
    main()
