#!/usr/bin/env python3
"""
ulti_theme_tracker.py — watch ULTI's theme rotation and roster churn over time.

ULTI (REX Shares) is an actively-traded thematic momentum fund: it turns its
~20-name speculative basket over almost completely month to month, rotating
between themes (e.g. nuclear/uranium -> quantum between May and June 2026).
The daily holdings history captures every snapshot; this turns that time series
into a readable rotation report so the drift is visible as it happens instead of
reconstructed after the fact.

Outputs (regenerated by the daily scrape pipeline):
  • analyses/ulti_rotation.md                      — human-readable report
  • etf-dashboard/public/data/ulti_rotation.json   — machine-readable (dashboard)

Run standalone any time:
    python3 scripts/ulti_theme_tracker.py

Maintaining the theme map: any holding not in THEME lands in an "Unmapped"
bucket and is listed loudly at the top of the report — add it to THEME below.
"""
import csv
import glob
import json
import os
from collections import defaultdict, OrderedDict
from datetime import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HISTORY = os.path.join(ROOT, "etf-dashboard", "public", "data", "history")
MD_OUT = os.path.join(ROOT, "analyses", "ulti_rotation.md")
JSON_OUT = os.path.join(ROOT, "etf-dashboard", "public", "data", "ulti_rotation.json")
FUND = "ULTI"

# ── Theme map. Extend as ULTI rotates into new names (Unmapped flags them). ──
THEME = {
    # Bitcoin / crypto miners
    "CLSK": "Bitcoin miners", "RIOT": "Bitcoin miners", "CIFR": "Bitcoin miners",
    "WULF": "Bitcoin miners", "CORZ": "Bitcoin miners", "IREN": "Bitcoin miners",
    "APLD": "Bitcoin miners", "MARA": "Bitcoin miners", "BTDR": "Bitcoin miners",
    "HUT": "Bitcoin miners", "BITF": "Bitcoin miners",
    # Quantum computing
    "IONQ": "Quantum", "RGTI": "Quantum", "QBTS": "Quantum", "QUBT": "Quantum",
    # Space
    "ASTS": "Space", "LUNR": "Space", "RDW": "Space", "RKLB": "Space", "PL": "Space",
    # Rare earth / critical materials
    "USAR": "Rare earth/materials", "TE": "Rare earth/materials", "MP": "Rare earth/materials",
    "CRML": "Rare earth/materials", "UAMY": "Rare earth/materials",
    # Drones / defense
    "ONDS": "Drones/defense", "UMAC": "Drones/defense", "RCAT": "Drones/defense",
    "KTOS": "Drones/defense", "AVAV": "Drones/defense",
    # Semis / photonics
    "POET": "Semis/photonics", "NVTS": "Semis/photonics", "WOLF": "Semis/photonics",
    "AXTI": "Semis/photonics", "LITE": "Semis/photonics", "AAOI": "Semis/photonics",
    "CRDO": "Semis/photonics", "AEHR": "Semis/photonics", "LWLG": "Semis/photonics",
    # Clean / alt energy
    "ENPH": "Clean energy", "FCEL": "Clean energy", "SEDG": "Clean energy",
    "BE": "Clean energy", "PLUG": "Clean energy", "RUN": "Clean energy",
    # Nuclear / uranium
    "OKLO": "Nuclear/uranium", "SMR": "Nuclear/uranium", "UEC": "Nuclear/uranium",
    "UUUU": "Nuclear/uranium", "LEU": "Nuclear/uranium",
    # Crypto-adjacent financials
    "GLXY": "Crypto financials", "COIN": "Crypto financials", "BMNR": "Crypto financials",
    "HOOD": "Crypto financials", "CRCL": "Crypto financials", "ASST.UQ": "Crypto financials",
    # AI / cloud compute
    "CRWV": "Cloud/AI", "NBIS": "Cloud/AI", "PATH": "Cloud/AI", "FSLY": "Cloud/AI",
    "TTD": "Cloud/AI", "DOCN": "Cloud/AI",
    # Fintech
    "UPST": "Fintech", "SOFI": "Fintech", "AFRM": "Fintech", "KLAR": "Fintech",
    "LMND": "Fintech", "FIGR": "Fintech",
    # Healthcare / biotech
    "HIMS": "Healthcare/biotech", "SMMT": "Healthcare/biotech", "OCUL": "Healthcare/biotech",
    "LQDA": "Healthcare/biotech",
    # Other one-offs seen in the history
    "ALAB": "Semis/photonics", "COHR": "Semis/photonics", "INTC": "Semis/photonics",
    "SNDK": "Semis/photonics", "OUST": "Semis/photonics", "FCEL.UQ": "Clean energy",
    "FLY": "Space", "AMPX": "Battery", "CDE": "Precious metals", "BW": "Industrials",
    "PCT": "Other", "CAR": "Other", "SOC": "Other", "VG": "Other",
}


def _f(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def load_equities(path):
    """Return {ticker: weight%} for ULTI's equity sleeve (excludes options/cash)."""
    out = {}
    with open(path, newline="") as f:
        for r in csv.DictReader(f):
            if r.get("ETF Ticker") != FUND or (r.get("Option_Type") or "").strip():
                continue
            tk = (r.get("Ticker") or "").strip()
            name = (r.get("Name") or "").upper()
            if (tk in ("", "OTHER", "CASH", "Cash&Other") or tk.upper().startswith("CASH")
                    or "FGXXX" in tk or "GOVT" in name or "MMKT" in name or "CASH" in name):
                continue
            w = _f(r.get("Weight")) or 0.0
            if w > 0:
                out[tk] = out.get(tk, 0.0) + w
    return out


def weekly_samples():
    """One snapshot per ISO week (the latest date in each week), oldest->newest."""
    files = sorted(glob.glob(os.path.join(HISTORY, f"holdings_*.csv")))
    by_week = OrderedDict()
    for path in files:
        ds = os.path.basename(path)[len("holdings_"):-len(".csv")]
        try:
            d = datetime.strptime(ds, "%Y-%m-%d").date()
        except ValueError:
            continue
        eq = load_equities(path)
        if not eq:  # ULTI absent / no equities that day
            continue
        by_week[d.isocalendar()[:2]] = (ds, eq)  # later date in week overwrites
    return list(by_week.values())


def theme_weights(eq):
    th = defaultdict(float)
    for tk, w in eq.items():
        th[THEME.get(tk, "Uncategorized")] += w
    return dict(th)


def build():
    samples = weekly_samples()
    if not samples:
        print("No ULTI history found."); return None
    samples = samples[-12:]  # last ~12 weeks keeps the timeline readable
    dates = [d for d, _ in samples]
    weights = [theme_weights(eq) for _, eq in samples]
    rosters = [set(eq) for _, eq in samples]

    all_themes = sorted(
        {t for w in weights for t in w},
        key=lambda t: -weights[-1].get(t, 0.0),
    )
    # Unmapped tickers in the latest snapshot — surface loudly.
    latest_eq = samples[-1][1]
    unmapped = sorted(tk for tk in latest_eq if tk not in THEME)

    # Roster churn between the two most recent samples.
    added = sorted(rosters[-1] - rosters[-2]) if len(rosters) > 1 else []
    dropped = sorted(rosters[-2] - rosters[-1]) if len(rosters) > 1 else []
    held = sorted(rosters[-1] & rosters[-2]) if len(rosters) > 1 else sorted(rosters[-1])
    # Churn rate: fraction of the book replaced since the prior sample.
    churn = (len(added) / len(rosters[-1])) if rosters[-1] else 0.0

    payload = {
        "fund": FUND,
        "asOf": dates[-1],
        "holdings": len(latest_eq),
        "dates": dates,
        "themes": all_themes,
        "timeline": [{"date": d, "weights": w} for d, w in zip(dates, weights)],
        "currentThemes": {t: round(weights[-1].get(t, 0.0), 1) for t in all_themes},
        "churnSincePrior": {"added": added, "dropped": dropped, "held": held,
                             "rate": round(churn, 2)},
        "unmapped": unmapped,
    }
    return payload, dates, all_themes, weights


def render_md(payload, dates, themes, weights):
    L = []
    L.append("# ULTI — Theme Rotation & Roster Churn\n")
    L.append(f"_Auto-generated from daily holdings. As of **{payload['asOf']}** "
             f"· {payload['holdings']} holdings · last {len(dates)} weekly samples._\n")
    if payload["unmapped"]:
        L.append(f"> ⚠️ **Unmapped tickers** (add to `THEME` in the tracker): "
                 f"{', '.join(payload['unmapped'])}\n")

    # Current allocation
    L.append("## Current theme allocation\n")
    L.append("| Theme | Weight |")
    L.append("|-------|-------:|")
    for t in themes:
        w = payload["currentThemes"].get(t, 0.0)
        if w > 0:
            L.append(f"| {t} | {w:.1f}% |")
    L.append("")

    # Drift timeline (themes x weeks)
    L.append("## Theme-weight drift (weekly)\n")
    hdr = "| Theme | " + " | ".join(d[5:] for d in dates) + " |"
    sep = "|-------|" + "|".join(["----:"] * len(dates)) + "|"
    L.append(hdr); L.append(sep)
    for t in themes:
        row = [f"{w.get(t, 0.0):.0f}" if w.get(t, 0.0) > 0 else "·" for w in weights]
        L.append(f"| {t} | " + " | ".join(row) + " |")
    L.append("")

    # Roster churn
    c = payload["churnSincePrior"]
    L.append("## Roster churn (latest week vs prior sample)\n")
    L.append(f"- **{int(c['rate']*100)}% of the book turned over** this step.")
    if c["added"]:
        L.append(f"- 🟢 **Added:** {', '.join(c['added'])}")
    if c["dropped"]:
        L.append(f"- 🔴 **Dropped:** {', '.join(c['dropped'])}")
    L.append(f"- ⚪ **Held:** {', '.join(c['held']) if c['held'] else '(none)'}")
    L.append("")
    return "\n".join(L)


def main():
    res = build()
    if not res:
        return
    payload, dates, themes, weights = res
    os.makedirs(os.path.dirname(MD_OUT), exist_ok=True)
    os.makedirs(os.path.dirname(JSON_OUT), exist_ok=True)
    with open(MD_OUT, "w") as f:
        f.write(render_md(payload, dates, themes, weights))
    with open(JSON_OUT, "w") as f:
        json.dump(payload, f, indent=2)
    print(f"Wrote {os.path.relpath(MD_OUT, ROOT)} and {os.path.relpath(JSON_OUT, ROOT)}")
    if payload["unmapped"]:
        print("Unmapped tickers:", ", ".join(payload["unmapped"]))


if __name__ == "__main__":
    main()
